### ISSUE TITLE
extensions/firestore-bigquery-export: "Request contains an invalid argument" on install

### ISSUE THREAD

**Issue by zchauvin** [firebase/extensions#319]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your configuration

- Extension name: `firestore-bigquery-export`
- Extension version: 0.1.5
- Configuration values: see screenshot

![Screen Shot 2020-05-21 at 9 12 17 AM](https://user-images.githubusercontent.com/7321305/82580667-4b33f880-9b44-11ea-9742-d923cd96ecd8.png)

### [REQUIRED] Step 3: Describe the problem

Even with default parameters (us-central-1, posts, firestore-export, posts), the extension installation fails with "Request contains an invalid argument". 

#### Steps to reproduce:

1. Attempt to install the extension with default parameters (us-central-1, posts, firestore-export, posts).
2. Observe that the installation request hangs forever after displaying "Request contains an invalid argument". 

Note that this issue repros if I already have an instance of the extension installed, or if I do not have any instances of the extension installed already. 

##### Expected result

The extension installs successfully. 

##### Actual result

The extension fails to install with a "Request contains an invalid argument" error.

**Comment by russellwheatley** [comment]
Hi @zchauvin, thanks for reporting this issue. I think there is a good chance that the problem has been resolved now as I successfully installed the BigQuery extension from the CLI and the console. Could you please try and report back? Thank you.

**Comment by zchauvin** [comment]
I was able to install the extension @russellwheatley, thanks for the followup!

**Comment by russellwheatley** [comment]
No problem, @zchauvin. Thanks for letting us know!

**Comment by SimonPrague** [comment]
Unfortunately I'm still experiencing this problem and I can't upgrade :cry: 

![2020-11-20_13-50](https://user-images.githubusercontent.com/47515740/99802124-6b666380-2b37-11eb-84da-91f4a8f820ee.png)

**Comment by russellwheatley** [comment]
Hey @jhuleatt, this is a problem when trying to upgrade to the latest BQ extension from the console UI. I looked at the response from the Firebase Server:

```
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  }
}

```

My assumption is that the backend hasn't been updated to accept the dataset location parameter, perhaps?

**Comment by jhuleatt** [comment]
Thanks for the heads up @russellwheatley! This turned out to be a bug in the Extensions backend, and we have a fix in the works. Given that this isn't a bug with a specific extension in this repository, I'm going to close out the issue.

For those stuck on this, the workaround is to [update via the CLI](https://firebase.google.com/docs/extensions/manage-installed-extensions?platform=cli#update-version).
